title: OpenSVBRDF
url: "https://opensvbrdf.github.io/"
description: First large-scale database of measured SVBRDFs.

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: true
favicon: true
favicon_location: "/assets/img/title.png"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Database"
   link: "http://www.cad.zju.edu.cn/home/opensvbrdf/"
 - name: "Challenges"
   link: "http://www.cad.zju.edu.cn/home/opensvbrdf/"
 - name: "Source Code"
   link: "https://github.com/OpenSVBRDF/OpenSVBRDF_source_code/"

footer: true
# footer_url: mailto:xiaohema1998@gmail.com
footer_text: "Contact: xiaohema1998@gmail.com"